### ISSUE TITLE
Faster construction of `PolygonArray` and `MultiPolygonArray`

### ISSUE THREAD

**Issue by philipc2** [holoviz/spatialpandas#122]
I am working with a relatively large unstructured grid (57,000,000 polygons) that I am aiming to visualize. I am storing my geometries in a `spatialpandas.GeoDataFrame` with a single `MultiPolygonArray` column. However, the time that it takes me to construct these lead to about a 6-7x slowdown over using a `geopandas.GeoDataFrame` with the same data stored.

#### Code / Algorithm 
```Python
import uxarray as ux
import numpy as np
import spatialpandas
import geopandas 
import antimeridian
from shapely import polygons as Polygons

def to_gdf(uxgrid):

    # construct an array of shapely polygons
    polygons = Polygons(uxgrid.polygon_shells)
    
    # indices of polygons that need to be corrected for the antimeridian case
    antimeridian_indices = np.argwhere(np.any(np.abs(np.diff(uxgrid.polygon_shells[:, :, 0])) >= 180, axis=1)).squeeze()
    
    # obtain antimeridian polygons
    antimeridian_polygons = polygons[antimeridian_indices]
    
    # correct antimeridian polygons, stored as MultiPolygons
    corrected_polygons = [antimeridian.fix_polygon(P) for P in antimeridian_polygons]
    
    # replace original polygon with the corrected version
    for i in reversed(antimeridian_indices):
        polygons[i] = corrected_polygons.pop()
    
    ## ---- spatialpandas
    geometry = MultiPolygonArray(polygons)
    gdf = spatialpandas.GeoDataFrame({"geometry": geometry})  

    ## ---- geopandas
    # gdf = geopandas.GeoDataFrame({"geometry": polygons})  
    
    return gdf
```

#### Timings
| Method / # of Polygons | 1 ,791 | 7,153 | 28,57 | 236,853 | 56,623,106 | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| SpatialPandas  | 0.117s | 0.401s | 1.61s | 12.4s | 2851s | 
| GeoPandas  |  0.043s | 0.111s | 0.553s | 2.53s | 434s | 

Taken from a single NCAR Casper Node with 256gb of memory (dataset was able to fit into memory each time, no dask used)

#### Question
My key question is whether there's a suggested or faster way of constructing `PolygonArray` and `MultiPolygonArray` or better ways of handling such large datasets. Thanks!

**Comment by ianthomas23** [comment]
I am not aware of a better approach to speed this up. Certainly creating `spatialpandas` geometry arrays includes some potentially slow copying of data and iterating over sequences, which could be better.

There is some hope for improvement on the horizon though. We have been looking into replacing some of the `spatialpandas` internal ragged arrays with `awkward` arrays, which will provide improvements in both speed and maintainability. This is proceeding relatively slowly though as it is not a high priority for any of the interested parties.
