### ISSUE TITLE
Pandas 2.2.0 rc0 emit warning

### ISSUE THREAD

**Issue by hoxbro** [holoviz/spatialpandas#137]
When trying out Pandas 2.2.0rc0 in https://github.com/holoviz/holoviews/pull/6074, I found the following warning started to be emitted: `Passing a SingleBlockManager to GeoSeries is deprecated and will raise in a future version. Use public APIs instead.`

**Comment by Hoxbro** [comment]
Inspiration to how to solve it can be found here: https://github.com/geopandas/geopandas/pull/3046
