### ISSUE TITLE
site is down

### ISSUE THREAD

**Issue by rbavery** [holoviz/spatialpandas#139]
https://spatialpandas.holoviz.org/

https://datashader.org/user_guide/Polygons.html# links to https://spatialpandas.holoviz.org/

which gives DNS_PROBE_FINISHED_NXDOMAIN

**Comment by philippjfr** [comment]
Thanks, not sure why it links there, I don't think we've ever had proper docs for spatialpandas, the only docs we do have are here:

https://nbviewer.org/github/holoviz/spatialpandas/blob/main/examples/Overview.ipynb
