### ISSUE TITLE
How is it different from geopandas?

### ISSUE THREAD

**Issue by Casyfill** [holoviz/spatialpandas#14]
just asking :-)

**Comment by jonmmease** [comment]
Hi @Casyfill,

The best discussion of differences in goals is probably https://github.com/holoviz/spatialpandas/issues/1#issuecomment-547496327.  But the discussion of the entire issue (https://github.com/holoviz/spatialpandas/issues/1) may be informative.

The initial motivation/application was to support polygon rendering in Datashader (https://github.com/holoviz/datashader/pull/826).

**Comment by Casyfill** [comment]
thanks!
