### ISSUE TITLE
Graceful handling of NoneTypes

### ISSUE THREAD

**Issue by brl0** [holoviz/spatialpandas#27]
An error is generated when converting a GeoPandas dataframe containing NoneTypes in the geometry column to a spatialpandas GeoDataFrame.  For example:
`ValueError: 
Received invalid value of type NoneType. Must be an instance of Point,
or MultiPoint`

It would be nice if NoneTypes were handled gracefully.

**Comment by jonmmease** [comment]
Thanks for the report.  Yeah, None's should get translated to nulls in the pyarrow ragged array.

**Comment by jonmmease** [comment]
Done in 0.3.4
