### ISSUE TITLE
More intuitive error when lsuffix == rsuffix on sjoin

### ISSUE THREAD

**Issue by balast** [holoviz/spatialpandas#35]
Right now, callling `joined = spd.sjoin(sddf, sdf, how='inner', lsuffix='leftsuffix', rsuffix='rightsuffix')` results in `RecursionError: maximum recursion depth exceeded while calling a Python object`.

It'd be nice to have a Exception message saying something like "lsuffix and rsuffix must not be equal"

**Comment by jbednar** [comment]
Sure! PR gratefully accepted, if you're able!

**Comment by balast** [comment]
I can't commit to making the PR right now, but I wanted to at least get this documented for others.  This would probably make a good first issue if someone is looking to contribute.

**Comment by brl0** [comment]
This was addressed in #37 and can probably be closed now.

**Comment by balast** [comment]
Awesome, thanks!
