### ISSUE TITLE
adding to conda forge

### ISSUE THREAD

**Issue by AndrewAnnex** [holoviz/spatialpandas#40]
hey all, I wanted to add this project to the conda-forge so I went ahead and made a recipe using grayskull. 
https://github.com/conda-forge/staged-recipes/pull/12138
if @jonmmease or others could confirm they are interested in helping maintain the conda-forge feedstock please let me know

**Comment by AndrewAnnex** [comment]
well, that happened faster than anticipated (or desired..) https://github.com/conda-forge/spatialpandas-feedstock

**Comment by jbednar** [comment]
Cool, thanks!
