### ISSUE TITLE
Apache Arrow 1.0.0 incompatibility

### ISSUE THREAD

**Issue by brl0** [holoviz/spatialpandas#43]
[Apache Arrow 1.0.0](https://arrow.apache.org/blog/2020/07/24/1.0.0-release/) was released and is causing many tests to fail with errors such as `AttributeError: 'pyarrow.lib.ListScalar' object has no attribute 'value_type'`.

**Comment by jbednar** [comment]
Thanks. I don't see ListScalar anywhere in our code, so that symptom must be downstream of where the real issue is...

**Comment by brl0** [comment]
I did make a superficial effort on this, updating the appropriate `.value_type` calls to `.type`, but was still running into issues.
