### ISSUE TITLE
current version number

### ISSUE THREAD

**Issue by brl0** [holoviz/spatialpandas#44]
@jbednar,

Thanks for merging PR #37.

@jonmmease has previously released v0.3.5 (about 5 months ago, shortly after releasing v0.3.4, which was released on 2/21), even though it does not appear to have been tagged, but this version appears on the pyviz conda channel and on conda-forge.  The latest alpha release should be version v0.3.6a.

I am not sure what needs to happen to get this latest release on the pyviz conda channel, but if there is anything I need to do, please let me know.

**Comment by jbednar** [comment]
Avoiding ever having a release with no tags is precisely why we set up our other projects to release on a tag, so that tagging and releasing are one atomic operation.  I'll try to figure out what commit was released earlier as 0.3.5 and tag that, and also update the latest alpha tag to be 0.3.6a0.

**Comment by jbednar** [comment]
Ok, the latest alpha is now 0.3.6a0, and I've tagged e2db63f as 0.3.5; that's the only plausible SHA because it's one past the 0.3.4 release and the next commit wasn't until weeks after 0.3.5 packages appeared on pip. Thanks for the heads up!
