### ISSUE TITLE
Does spatialpandas read shapefiles or do I need to convert from geopandas?

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/spatialpandas#73]
as title says

**Comment by jbednar** [comment]
Spatialpandas objects have a `from_shapely` classmethod (see e.g. https://github.com/holoviz/spatialpandas/blob/master/spatialpandas/geometry/ring.py), which looks like it would work if you use Shapely to read it.

**Comment by brl0** [comment]
@andhuang-CLGX, I would definitely suggest reading shapefiles with geopandas and then converting that to a spatialpandas dataframe.

**Comment by jbednar** [comment]
We definitely do not want to try to make SpatialPandas compete with GeoPandas for what GeoPandas already does!

**Comment by brl0** [comment]
@rrpelgrim,

I think issue #1 is a great reference from the original author of the package on the topic. Specifically:

> ## Non-goals
> spatialpandas will be focused on geometry only, not geography. As such:
> -  No built-in support for loading data from geography-specific file formats
> -  No dependency on GDAL/fiona
> -  No coordinate reference frame logic
> 

I do wonder if some projects like [pyshp](https://github.com/GeospatialPython/pyshp), which was previously mentioned, would benefit from offering spatialpandas as an output option.

I think spatialpandas is great for us, particularly for distributed workloads, but considering some of the great work they have been doing on [dask-geopandas](https://github.com/geopandas/dask-geopandas), so I'm not sure how much additional value it offers the ecosystem to add many more features here.  That said, I think if other lightweight geospatial packages were interoperable with it, it could be very beneficial for users looking to avoid the heavier and occasionally fragile stack of dependencies geopandas is built on top of.  But it is hard to imagine ever approaching feature parity, considering the amazing depth of functionality that stack provides.

It should also be noted, that ultimately this project is under the holoviz team organization, who potentially, and justifiably, may be somewhat sensitive to adding features that would become future maintainability challenges.

**Comment by jbednar** [comment]
We at HoloViz would never complain about other packages like pyshp generating spatialpandas compatible output. 🙂

The original author of issue 1 had moved on from our group, so it's up to me now, I guess. BTW, we will soon be looking at whether Awkward arrays could work as a basis for spatialpandas, and if so the task would then be to connect pyshp with Awkward. Can't really look at that until June, though!

**Comment by brl0** [comment]
@jbednar, Your timing in mentioning Awkward is well timed, I literally just clicked to this notification coming from [dask-awkward](https://github.com/ContinuumIO/dask-awkward).  It is exciting to see you guys moving that forward.  :)

Coincidences aside, I really appreciate the efforts, both voluntary and involuntary, you and your team put in to supporting the community, and the same goes for @jorisvandenbossche and the geopandas team.  It's amazing how much work and effort goes into building up this ecosystem.
