### ISSUE TITLE
Process for creating new release

### ISSUE THREAD

**Issue by brl0** [holoviz/spatialpandas#83]
@philippjfr, @jbednar,

I tried to create a new release, as I thought I had done before, but the build [failed](https://github.com/holoviz/spatialpandas/runs/3270122946?check_suite_focus=true#step:9:25).  It appears that the version information param is finding is not what I intended.
What is the correct process for creating a release?

Thanks in advance for your guidance and support.

**Comment by jbednar** [comment]
With our other projects the process is simply `git tag -a -m 'Version X.Y.Z' vX.Y.z; git push origin vX.Y.z'; not sure if we've set up spatialpandas the same way.

**Comment by brl0** [comment]
That did the trick, thanks for the guidance!

The initial attempt at creating the release was performed through the GitHub interface.  This creates a tag, but `git describe` still returned the old version info, however `git describe --tags` did show the new tag.  Deleting the tag, then tagging and pushing as suggested seemed to solve the problem.
