### ISSUE TITLE
Fixes required for new release

### ISSUE THREAD

**Issue by ianthomas23** [holoviz/spatialpandas#86]
I am planning to get this into a state suitable for a new release. There are many test failures:

* Pandas extension array related failures.
* Parquet related failures (#84 may be relevant).
* Geometry intersection issues (#61 may be relevant).
* Shapely deprecation warnings, partly fixed by #85.

I am also planning to drop Python 3.6 support and add 3.9 and 3.10.

This is too much to do in a single PR so I will do multiple targetted PRs which will all be failing part of CI until they are all combined.

**Comment by jbednar** [comment]
Our hero!

**Comment by ianthomas23** [comment]
- Pandas extension array failures fixed by #88
- Parquet-related failures fixed by #92
- Geometry intersection tests failures fixed by #90
- Shapely deprecation warnings fixed by #85
